### ISSUE TITLE
Week 4 Submission

### ISSUE THREAD

**Issue by jtan12** [jtan12/week4-asmt-twitter#2]
/cc @codepathreview

**Comment by jtan12** [comment]
Hello @codepathreview. I seem to be having an issue with pushing to Github. I am not seeing my .gitignore, my Pods folders, and .xcworkspace, as in the previous assignments. I am not sure what the problem is as I've used the same methods to commit and push from before. When I commit, there are no new files to be committed. However, I am checking now on the website and it seems only my app folder is pushed. Thanks.

**Comment by jtan12** [comment]
/cc @codepathreview

Disregard previous comment. I have downloaded Github desktop and synced the other files through there instead of Source Control. I believe I might not have created a working copy of the Pods in the beginning, which is why it did not sync to Github. All the files should be there now and complete. Thanks.

**Comment by minhkhang1795** [comment]
Great! I see your whole project :sunglasses: 

:+1: Nice work! The point of this homework was to explore an example of a full MVC application with a RESTful API. 

We have a detailed [Project 4 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_4_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
